# Generated by Django 3.2.8 on 2021-10-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Pais', models.CharField(max_length=50)),
                ('gusta_hacer', models.CharField(max_length=50)),
                ('si_o_no', models.CharField(max_length=2)),
                ('que_piensas', models.TextField()),
                ('fecha_post', models.DateField()),
            ],
        ),
    ]
